# fly.toml app configuration file generated for house-hq-kartik on 2026-09-13T18:52:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'house-hq-kartik'
primary_region = 'lhr'

[build]
[env]
  DB_PATH = '/data/house.db'

[[mounts]]
  source = 'house_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
